### ISSUE TITLE
Duplicate entries in view of queue

### ISSUE THREAD

**Issue by ppannuto** [mterwill/classroom-help-queue#32]
<img width="426" alt="screen shot 2016-09-06 at 16 45 56" src="https://cloud.githubusercontent.com/assets/339422/18290436/6e0df266-7451-11e6-9de6-ded2dd99ddd6.png">

**Comment by ppannuto** [comment]
This one seems to be transient. Went away on refresh.

Good luck 💃

**Comment by mterwill** [comment]
Closed in 9b8dc8a95711a234413de6e58c359f31a48d855a. Went away because you were not an instructor the first time, then on refresh you were.
