### ISSUE TITLE
Allow users on group project to enqueue as group

### ISSUE THREAD

**Issue by ahyerman** [mterwill/classroom-help-queue#66]
It would be a nice feature to allow if one group member is on the queue to allow all members to be visible that place, this way a group can still remain on the queue even when the requestor needs to leave.

**Comment by wkacsur** [comment]
+1

**Comment by mterwill** [comment]
@ahyerman: would #73 address this?

tl;dr of that issue: instructors set queues to "group" or "individual" mode. groups are predefined by the instructors to prevent abuse. queue works as normal, except a request shows up per group rather than per individual.

**Comment by ahyerman** [comment]
@mterwill: yes, that sounds nice
