### ISSUE TITLE
edit location

### ISSUE THREAD

**Issue by maxgittelman** [mterwill/classroom-help-queue#68]
after submitting, you should be able to change your location (quite often I find myself moving into a room when space becomes available or kicked out from my spot)

**Comment by mterwill** [comment]
This functionality was added in fd6bcd1f3f84c6e93b230955ebe8c5320dd5df7f. After submitting a request, press "Edit" and you will be able to update your location.

<img width="427" alt="screen shot 2016-12-13 at 2 47 26 pm" src="https://cloud.githubusercontent.com/assets/5882053/21156248/2519df54-c143-11e6-9d9b-12c063015521.png">
