### ISSUE TITLE
View queue after it closed

### ISSUE THREAD

**Issue by tlaredo** [mterwill/classroom-help-queue#79]
For students who are already on the queue after it closes, it would be helpful if we can still view the queue just to know if we're about to get seen.

**Comment by mterwill** [comment]
Can you not? A queue won't show up on the index page if it's closed, but the page is still accessible if you kept it open/have the URL.

![image](https://cloud.githubusercontent.com/assets/5882053/23682373/73897950-0361-11e7-9d22-8b96f9871b9f.png)

**Comment by tlaredo** [comment]
Yeah that's the issue I'm referring to... the fact that the queue no longer shows up on the index page if it's closed. This has happened to me (and other students) when we accidentally leave the page and can no longer see the queue even if we're still on it.
