### ISSUE TITLE
Show current spot in queue at top of page

### ISSUE THREAD

**Issue by eazellou** [mterwill/classroom-help-queue#80]
Say I'm 15th in the queue, and the queue has 34 people.

Showing 15 / 34 or even just 15 would be more useful than just showing the total size of the queue as it currently does.  

As a student in the queue, I don't really care how long the total queue is—I want to know how far back I am in line.

**Comment by mterwill** [comment]
The total queue size is useful information for instructors. I like the idea of showing your position as 15/34, though. Relates to #74.
